apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  type: NodePort
  ports:
    - port: 8080            # External service port
      targetPort: 8000       # Target port in the container
      nodePort: 32411        # Optionally specify the NodePort (or let Kubernetes assign one)
  selector:
    app: hello-node